// RootLayout.js

import { Inter } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react"
import AuthProvider from "./context/authprovider";
import Layout from "../components/Layout";

const inter = Inter({ subsets: ["latin"] });

/* export function metadata() {
  title: "QR Manager",
  description: "Generated by create next app",
} */

const RootLayout= ({
  children,
}) =>{
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider >
          <Layout session={session}> {/* Pasa la sesión al componente Layout */}
              {children}
          </Layout>
          <Analytics />
        </AuthProvider>
      </body>
    </html>
  );
}
export default RootLayout

