// RootLayout.js

import { Inter } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react"
import AuthProvider from "../context/authprovider";
import Layout from "../components/Layout";
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "QR Manager",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Layout > {/* Pasa la sesión al componente Layout */}
              {children}
          </Layout>
          <Analytics />
          <SpeedInsights/>
        </AuthProvider>
      </body>
    </html>
  );
}

